language: haskell
ghc:
  - 7.8

env:
  # CODECOV_TOKEN
  - secure: hZLoJprZHXqpGuyW3Dz8Hh+YpDogv+iOs3PGeMW65TZCLnGADrmmxk2Im1h4MwZBmzXe7JVTXrgNJe3ZEMnGVP3OtDj4Srb16xGlSW/DhT7wLLsE9eXQshfw+4xhPdu2y8ht62+wqzyg4VkrPDooDcGRgekD4JLO4A4/LhJYxAZCizBcv9uQwPxtrMVrxNiPQfsiH5FmWUPM6Z6Xa4URxjGYU82yCOulYxhs+4WL6Apj+/GouWcaUP4C8tw58klTRHCOoa4VABgG5QZhV0BoNscJWMlEJJQTHtjGmMqBwMPEFJ7yCB5CTz/VeDGQaKp0rvQyWE0EwBvJynGg0+/blYgLdVHecv/SKGP5yWD3y066HQfdprMZEfsw+Vx6A0tUl8eyNRANEzZZHMrGmtDDnwFinXcSQG70cDgPEcRbBtbp2nhrqUzQOWEQ1pscSUb7EOcxGAEH+DZjmOYmvq8BLTYHk7axgzxA/xNyhM4l/+z1oSUj/vnXixAqd5rIgXMrgDmrDDBbYit/H7fd5+bsjsd7qNx5ll1n+I1VflZ7Z/pPwruQ/9qOM6L3QyCTTCD72wwn45cxkY7YHgyxsXCuvWbvEB6jAO3vN70owNtysTH0EE1uQILtTrCy1aM1j0/L0ywVRubSPZno6xZr49FbZbWnku3FlJomw1a7RZm76V4=

cache:
  directories:
    - $HOME/.cabal/bin
    - $HOME/.cabal/share

before_install:
  - "[[ $(~/.cabal/bin/cabal --numeric-version) =~ ^1\\.20\\. ]]
     && ~/.cabal/bin/alex -v
     && ~/.cabal/bin/happy -v
     || cabal install --constraint='transformers installed' -j3
        happy alex 'cabal-install >=1.20 && <1.21'"
  - export PATH=$HOME/.cabal/bin:$PATH

install:
  - "cat >> cabal.config <<<'flags: -test-coverage'"
  - cabal install --only-dependencies --enable-tests -j3

after_script:
  # Ugly hack because codecov-haskell 0.3.0 doesn't support token and 0.4.0 is
  # not yet on Hackage.
  - "cabal install -j3 'codecov-haskell >=0.3 && <0.4'
    && cabal clean
    && cabal configure --enable-tests --enable-library-coverage
    && (cabal test tests || :)
    && codecov-haskell --display-report --dont-send tests >coverage-file
    && cat coverage-file
    && (curl -d @coverage-file -i -o - -S --retry 3
    \"https://codecov.io/upload/v1?\
    travis_job_id=$TRAVIS_JOB_ID&\
    commit=$TRAVIS_COMMIT&\
    branch=$TRAVIS_BRANCH&\
    pull_request=${TRAVIS_PULL_REQUEST/false/}&\
    token=$CODECOV_TOKEN\";
    echo)"
