language: haskell
ghc:
  - 7.8

env:
  global:
    # CODECOV_TOKEN
    - secure: hZLoJprZHXqpGuyW3Dz8Hh+YpDogv+iOs3PGeMW65TZCLnGADrmmxk2Im1h4MwZBmzXe7JVTXrgNJe3ZEMnGVP3OtDj4Srb16xGlSW/DhT7wLLsE9eXQshfw+4xhPdu2y8ht62+wqzyg4VkrPDooDcGRgekD4JLO4A4/LhJYxAZCizBcv9uQwPxtrMVrxNiPQfsiH5FmWUPM6Z6Xa4URxjGYU82yCOulYxhs+4WL6Apj+/GouWcaUP4C8tw58klTRHCOoa4VABgG5QZhV0BoNscJWMlEJJQTHtjGmMqBwMPEFJ7yCB5CTz/VeDGQaKp0rvQyWE0EwBvJynGg0+/blYgLdVHecv/SKGP5yWD3y066HQfdprMZEfsw+Vx6A0tUl8eyNRANEzZZHMrGmtDDnwFinXcSQG70cDgPEcRbBtbp2nhrqUzQOWEQ1pscSUb7EOcxGAEH+DZjmOYmvq8BLTYHk7axgzxA/xNyhM4l/+z1oSUj/vnXixAqd5rIgXMrgDmrDDBbYit/H7fd5+bsjsd7qNx5ll1n+I1VflZ7Z/pPwruQ/9qOM6L3QyCTTCD72wwn45cxkY7YHgyxsXCuvWbvEB6jAO3vN70owNtysTH0EE1uQILtTrCy1aM1j0/L0ywVRubSPZno6xZr49FbZbWnku3FlJomw1a7RZm76V4=
  matrix:
    - TESTS=spec
    - TESTS=qa

cache:
  directories:
    - $HOME/.cabal/bin
    - $HOME/.cabal/share

before_install:
  - |
    declare -a p
    [[ $(~/.cabal/bin/cabal --numeric-version) =~ ^1\.20\. ]] ||
      p+=('cabal-install >=1.20 && <1.21')
    ~/.cabal/bin/alex -v || p+=(alex)
    ~/.cabal/bin/happy -v || p+=(happy)
    ~/.cabal/bin/codecov-haskell -V || p+=('codecov-haskell >=0.3 && <0.4')
    ~/.cabal/bin/hlint -V || p+=('hlint >=1 && <2')
    ! ((${#p[@]})) ||
      cabal install --constraint='transformers installed' -j3 "${p[@]}"
  - export PATH=$HOME/.cabal/bin:$PATH

install:
  - cabal sandbox init
  - |
    flags="-test-coverage -test-style"
    if [[ $TESTS == qa ]]; then
      echo flags: $flags -test-spec test-examples test-documentation
    else
      echo flags: $flags test-spec -test-examples -test-documentation
    fi >> cabal.config
  - cabal install --only-dependencies --enable-tests -j3

script:
  - |
    if [[ $TESTS == spec ]]; then
      cabal configure --enable-tests --enable-library-coverage
    else
      cabal configure --enable-tests
    fi && cabal build && cabal test
  - if [[ $TESTS == qa ]]; then hlint benchmark library test-suite; fi

after_script:
  # Ugly hack because codecov-haskell 0.3.0 doesn't support token and 0.4.0 is
  # not yet on Hackage.
  - "if [[ $TESTS == spec ]]; then
    codecov-haskell --display-report --dont-send tests >coverage-file
    && cat coverage-file
    && (curl -d @coverage-file -i -o - -S --retry 3
    \"https://codecov.io/upload/v1?\
    travis_job_id=$TRAVIS_JOB_ID&\
    commit=$TRAVIS_COMMIT&\
    branch=$TRAVIS_BRANCH&\
    pull_request=${TRAVIS_PULL_REQUEST/false/}&\
    token=$CODECOV_TOKEN\";
    echo); fi"
